# Generated by Django 4.2.2 on 2023-06-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0002_rename_author_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tittle',
            new_name='Title',
        ),
    ]
